/**
 * Normalised catalogue identities: one record per product, one per purchasable
 * variant (SKU).
 *
 * Until now a SKU was only ever the pair (product id, free-text size label),
 * repeated in inventory, pricing, carts, orders and restock requests. This
 * gives each variant a stable id and keeps the old pair as `legacyStockKey`,
 * the explicit compatibility map back to every existing row.
 *
 * Derived from the catalogue file, and seeded into `catalog_products` /
 * `catalog_variants` by migration 0014 (generated by
 * `scripts/catalog-seed-sql.ts`). Pure: safe in the browser.
 */
import type { Product } from '@/data/mock-data';
import { skuKey } from '@/modules/catalog/sku-price';

export type CatalogProductRecord = {
  id: string;
  slug: string;
  name: string;
  category: string;
};

export type CatalogVariantRecord = {
  /** Stable SKU id, e.g. `retinol-90ml`. Never reused for a different size. */
  id: string;
  productId: string;
  /** `productId::size`, the key every pre-0014 row is stored under. */
  legacyStockKey: string;
  sizeLabel: string;
  /**
   * Millilitres when the label states millilitres, otherwise null. Grams,
   * pads, patches and masks are not converted: that would need a density or
   * fill weight nobody has supplied.
   */
  volumeMl: number | null;
};

export function variantId(productId: string, sizeLabel: string): string {
  // Whitespace dropped first, so "30ml", "30 ml" and "30 ML" are one id and a
  // duplicate is caught rather than becoming a second SKU for the same size.
  const size = sizeLabel.toLowerCase().replace(/\s+/g, '').replace(/[^a-z0-9.]+/g, '-').replace(/^-+|-+$/g, '');
  return `${productId}-${size}`;
}

export function volumeMl(sizeLabel: string): number | null {
  const m = /^\s*(\d+(?:\.\d+)?)\s*ml\s*$/i.exec(sizeLabel);
  return m ? Number(m[1]) : null;
}

export function catalogRecords(products: readonly Product[]): {
  products: CatalogProductRecord[];
  variants: CatalogVariantRecord[];
} {
  return {
    products: products.map(({ id, slug, name, category }) => ({ id, slug, name, category })),
    variants: products.flatMap((p) =>
      p.sizes.map((s) => ({
        id: variantId(p.id, s.label),
        productId: p.id,
        legacyStockKey: skuKey(p.id, s.label),
        sizeLabel: s.label,
        volumeMl: volumeMl(s.label),
      }))
    ),
  };
}

/**
 * Everything that would break the database constraints or an unambiguous
 * mapping: duplicate product ids, slugs, variant ids or legacy keys, and
 * prices that could never be charged. Empty means the catalogue is sound.
 */
export function catalogProblems(products: readonly Product[]): string[] {
  const problems: string[] = [];
  const { products: ps, variants } = catalogRecords(products);
  const dupes = (label: string, values: string[]) => {
    const seen = new Set<string>();
    for (const v of values) {
      if (seen.has(v)) problems.push(`Duplicate ${label}: ${v}`);
      seen.add(v);
    }
  };
  dupes('product id', ps.map((p) => p.id));
  dupes('slug', ps.map((p) => p.slug));
  dupes('variant id', variants.map((v) => v.id));
  dupes('legacy stock key', variants.map((v) => v.legacyStockKey));

  for (const p of products) {
    if (p.sizes.length === 0) problems.push(`No sizes: ${p.id}`);
    for (const s of p.sizes) {
      if (!Number.isInteger(s.price) || s.price <= 0) problems.push(`Impossible price: ${p.id} ${s.label} ${s.price}`);
    }
    if (p.salePrice !== undefined && (p.salePrice <= 0 || p.salePrice > p.price)) {
      problems.push(`Sale price above list price or not positive: ${p.id}`);
    }
  }
  return problems;
}
