import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Private storage for face-scan images. Never the CMS media store: CMS
 * media is public by design, and these photos must never be.
 *
 * Keys are generated by the server (`private/scans/<scan id>.jpg`; the
 * database refuses any other shape). Objects are read by the server only;
 * a short-lived signed token is the only way to grant read access, and no
 * public route serves these files.
 *
 * Adapters:
 * - `local` (PRIVATE_STORAGE=local): a git-ignored folder outside `public/`,
 *   for development and tests only.
 * - Production needs an S3-compatible bucket with private ACLs and scoped
 *   credentials. It is not configured, so hosted upload stays disabled
 *   there (see privateStorage()).
 */
export interface PrivateStorage {
  readonly kind: string;
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  delete(key: string): Promise<void>;
  /** Every object under private/scans/, with its last-modified time, for orphan cleanup. */
  list(): Promise<{ key: string; modifiedAt: Date }[]>;
}

/**
 * `private/scans/<scan id>.jpg`, or a staged per-request key
 * `private/scans/<scan id>.<nonce>.jpg`. Each upload request writes its own
 * staged object, so a request that loses a race deletes only its own bytes
 * (re-audit A13).
 */
const KEY_SHAPE = /^private\/scans\/[0-9a-f-]{36}(\.[0-9a-f]{16})?\.jpg$/;
export const scanObjectKey = (scanId: string) => `private/scans/${scanId}.jpg`;
export const stagedObjectKey = (scanId: string) => `private/scans/${scanId}.${randomBytes(8).toString('hex')}.jpg`;

export function localPrivateStorage(root: string): PrivateStorage {
  const resolve = (key: string) => {
    if (!KEY_SHAPE.test(key)) throw new Error('invalid private object key');
    return path.join(root, key);
  };
  return {
    kind: 'local',
    async put(key, bytes) {
      const file = resolve(key);
      await mkdir(path.dirname(file), { recursive: true });
      await writeFile(file, bytes, { mode: 0o600 });
    },
    async get(key) {
      try {
        return new Uint8Array(await readFile(resolve(key)));
      } catch {
        return null;
      }
    },
    async delete(key) {
      await rm(resolve(key), { force: true });
    },
    async list() {
      const dir = path.join(root, 'private', 'scans');
      const names = await readdir(dir).catch(() => [] as string[]);
      const out: { key: string; modifiedAt: Date }[] = [];
      for (const name of names) {
        const key = `private/scans/${name}`;
        if (!KEY_SHAPE.test(key)) continue;
        const info = await stat(path.join(dir, name)).catch(() => null);
        if (info) out.push({ key, modifiedAt: info.mtime });
      }
      return out;
    },
  };
}

/** The configured adapter, or null when private storage is not available (hosted upload is then disabled). */
export function privateStorage(): PrivateStorage | null {
  if (process.env.PRIVATE_STORAGE === 'local') return localPrivateStorage(path.join(process.cwd(), '.private-storage'));
  return null;
}

const secret = () => process.env.PRIVATE_STORAGE_SIGNING_SECRET || process.env.AUTH_SECRET || '';

/** A token granting read access to one object until `expiresAt` (at most 10 minutes ahead). */
export function signReadToken(key: string, expiresAt: number): string {
  if (!secret()) throw new Error('no signing secret configured');
  const exp = Math.min(expiresAt, Date.now() + 10 * 60_000);
  const mac = createHmac('sha256', secret()).update(`${key}\n${exp}`).digest('base64url');
  return `${exp}.${mac}`;
}

export function verifyReadToken(key: string, token: string, now = Date.now()): boolean {
  const [expText, mac] = token.split('.');
  const exp = Number(expText);
  if (!secret() || !Number.isFinite(exp) || exp < now || !mac) return false;
  const expected = createHmac('sha256', secret()).update(`${key}\n${exp}`).digest();
  const given = Buffer.from(mac, 'base64url');
  return given.length === expected.length && timingSafeEqual(given, expected);
}
