#!/usr/bin/env node
/**
 * A disposable, database-backed environment for desktop acceptance testing.
 *
 *   node scripts/acceptance-env.mjs init        # container + .env.acceptance.local (generated test values)
 *   node scripts/acceptance-env.mjs run <cmd>   # run a command with that environment
 *   node scripts/acceptance-env.mjs destroy     # remove the container and its data
 *
 * Everything here is local and synthetic: a Postgres container from the
 * local postgres:17 image on port 5435, generated secrets, a demo customer
 * identifier (its sign-in code is shown on screen; see lib/demo-access.ts),
 * a generated staff credential, sample orders allowed (no payment keys, so
 * only cash on delivery), local private storage. Values live only in the
 * git-ignored .env.acceptance.local and are never printed. Never point this
 * at a shared or production database.
 */
import { execFileSync, spawn } from 'node:child_process';
import { pbkdf2Sync, randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const FILE = '.env.acceptance.local';
const CONTAINER = 'avyora-acceptance-db';
const PORT = 5435;
const [cmd, ...rest] = process.argv.slice(2);

/** Same format as scripts/hash-password.mjs: pbkdf2:<iterations>:<salt>:<hash>, base64url. */
const pbkdf2Hash = (password) => {
  const salt = randomBytes(16);
  const bits = pbkdf2Sync(password, salt, 210_000, 32, 'sha256');
  return `pbkdf2:210000:${salt.toString('base64url')}:${bits.toString('base64url')}`;
};

const read = () =>
  Object.fromEntries(
    readFileSync(FILE, 'utf8')
      .split(/\r?\n/)
      .filter((l) => l && !l.startsWith('#') && l.includes('='))
      .map((l) => [l.slice(0, l.indexOf('=')), l.slice(l.indexOf('=') + 1)])
  );

if (cmd === 'init') {
  if (!existsSync(FILE)) {
    const secret = () => randomBytes(24).toString('base64url');
    const dbPassword = secret();
    const staffPassword = secret();
    const env = {
      ACCEPTANCE_DB_PASSWORD: dbPassword,
      DATABASE_URL: `postgresql://postgres:${dbPassword}@localhost:${PORT}/avyora`,
      DATABASE_REPLICA_URL: '',
      AUTH_SECRET: secret(),
      AUTH_URL: 'http://localhost:9006',
      AUTH_TRUST_HOST: 'true',
      CRON_SECRET: secret(),
      RATE_LIMIT_KEY_SECRET: secret(),
      DEMO_IDENTIFIERS: 'acceptance-customer@example.test,acceptance-second@example.test',
      ADMIN_USERNAME: 'acceptance-owner',
      ACCEPTANCE_ADMIN_PASSWORD: staffPassword,
      ADMIN_PASSWORD_HASH: pbkdf2Hash(staffPassword),
      SESSION_SECRET: secret() + secret(),
      NEXT_PUBLIC_REDESIGN: '1',
      NEXT_PUBLIC_FACE_SCAN: '1',
      FACE_SCAN_HOSTED: '1',
      PRIVATE_STORAGE: 'local',
      ALLOW_SAMPLE_ORDERS: '1',
      NEXT_PUBLIC_SITE_URL: 'http://localhost:9006',
      RESEND_API_KEY: '',
      EMAIL_FROM: '',
    };
    writeFileSync(FILE, `# Generated by scripts/acceptance-env.mjs. Local acceptance only; synthetic values.\n${Object.entries(env).map(([k, v]) => `${k}=${v}`).join('\n')}\n`, { mode: 0o600 });
  }
  const env = read();
  const running = execFileSync('docker', ['ps', '-a', '--filter', `name=^${CONTAINER}$`, '--format', '{{.Status}}']).toString().trim();
  if (!running) {
    execFileSync('docker', ['run', '-d', '--name', CONTAINER, '-e', `POSTGRES_PASSWORD=${env.ACCEPTANCE_DB_PASSWORD}`, '-e', 'POSTGRES_DB=avyora', '-p', `127.0.0.1:${PORT}:5432`, 'postgres:17'], { stdio: 'ignore' });
  } else if (!running.startsWith('Up')) {
    execFileSync('docker', ['start', CONTAINER], { stdio: 'ignore' });
  }
  console.log(`Acceptance database container ${CONTAINER} on 127.0.0.1:${PORT}; environment in ${FILE}.`);
} else if (cmd === 'run') {
  const child = spawn(rest[0], rest.slice(1), { stdio: 'inherit', shell: process.platform === 'win32', env: { ...process.env, ...read() } });
  child.on('exit', (code) => process.exit(code ?? 0));
} else if (cmd === 'destroy') {
  execFileSync('docker', ['rm', '-f', CONTAINER], { stdio: 'ignore' });
  console.log(`Removed ${CONTAINER}. ${FILE} is kept; delete it if no longer needed.`);
} else {
  console.error('usage: node scripts/acceptance-env.mjs init | run <command...> | destroy');
  process.exit(2);
}
